---
title: "Analysis"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(dplyr)
library(ggplot2)
library(data.table)
library(plm) # NOTE: You might need to install this
library(stargazer)
theme_set(theme_minimal())
```

```{r, eval = FALSE}
########### KAGGLE DATA ###############
########## START HERE #################

dat_kaggle <- readRDS("data/dat_kaggle.rds") 

#Change column names
names(dat_kaggle)[4] <- "Topic_1"
names(dat_kaggle)[5] <-"Topic_2"
names(dat_kaggle)[6] <-"Topic_3"
names(dat_kaggle)[7] <-"Topic_4"
names(dat_kaggle)[8] <-"Topic_5"
names(dat_kaggle)[9] <-"Topic_6"
names(dat_kaggle)[10] <-"Topic_7"
names(dat_kaggle)[11] <-"Topic_8"
names(dat_kaggle)[12] <-"Topic_9"
names(dat_kaggle)[13] <-"Topic_10"

#First, we will perform Least Squares Dummy Variables (LSDV) estimation with lm(), where we essentially get an individual estimate for each unit. Second, we will run our model with plm(), which will do the same mechanics, yet it will not render each of the units intercept.

str(dat_kaggle)
#trasnforming country to categorical variable
dat_kaggle$country=as.factor(dat_kaggle$country)

#Denmark
dat_kaggle$Denmark<-NA 
dat_kaggle$Denmark[dat_kaggle$country=="Denmark"]<-1
dat_kaggle$Denmark[is.na(dat_kaggle$Denmark)]<- 0
#USA
dat_kaggle$USA<-NA 
dat_kaggle$USA[dat_kaggle$country=="USA"]<-1
dat_kaggle$USA[is.na(dat_kaggle$USA)]<- 0
# India
dat_kaggle$India<-NA
dat_kaggle$India[dat_kaggle$country=="India"]<-1
dat_kaggle$India[is.na(dat_kaggle$India)]<- 0
# Japan
dat_kaggle$Japan<-NA
dat_kaggle$Japan[dat_kaggle$country=="Japan"]<-1
dat_kaggle$Japan[is.na(dat_kaggle$Japan)]<- 0
# UK
dat_kaggle$UK<-NA
dat_kaggle$UK[dat_kaggle$country=="UK"]<-1
dat_kaggle$UK[is.na(dat_kaggle$UK)]<- 0
# Canada
dat_kaggle$Canada<-NA
dat_kaggle$Canada[dat_kaggle$country=="Canada"]<-1
dat_kaggle$Canada[is.na(dat_kaggle$Canada)]<- 0
# France
dat_kaggle$France<-NA
dat_kaggle$France[dat_kaggle$country=="France"]<-1
dat_kaggle$France[is.na(dat_kaggle$France)]<- 0
# South Korea
dat_kaggle$SK<-NA
dat_kaggle$SK[dat_kaggle$country=="South Korea"]<-1
dat_kaggle$SK[is.na(dat_kaggle$SK)]<- 0
# Sweden
dat_kaggle$Sweden<-NA
dat_kaggle$Sweden[dat_kaggle$country=="Sweden"]<-1
dat_kaggle$Sweden[is.na(dat_kaggle$Sweden)]<- 0


# topics model
topics_only_model <- lm(rating ~ Topic_1 + Topic_2 + Topic_3 + Topic_4+ Topic_5+ Topic_6 + Topic_7 + Topic_8 + Topic_9 + Topic_10, data = dat_kaggle)
summary(topics_only_model)
stargazer(topics_only_model,type = "text", out = "Table 1", 
          title = "Topic Model: Which Topics have better rating?", 
          omit.stat=c("LL","ser","f","adj.rsq"), #omit character vector
          dep.var.labels.include = FALSE,
          column.labels = c("Rating"))

# Country Model
country_model <- lm(rating ~ USA + India + UK + Canada + France, data = dat_kaggle)
summary(country_model)
stargazer(country_model,type = "text", out = "Table 2", 
          title = "Country Model: USA, India, UK, Canada and France", 
          omit.stat=c("LL","ser","f","adj.rsq"), #omit character vector
          dep.var.labels.include = FALSE,
          column.labels = c("Rating"))

# Duration Model
duration_model <- lm(rating ~ duration, data = dat_kaggle)
summary(duration_model)
stargazer(duration_model,type = "text", out = "Table 3", 
          title = "Duration Model", 
          omit.stat=c("LL","ser","f","adj.rsq"), #omit character vector
          dep.var.labels.include = FALSE,
          column.labels = c("Rating"))
# longer films have higher ratings

# Horror Movies
sk_horror_model <- lm(rating ~ SK*Topic_6, data = dat_kaggle)
summary(sk_horror_model)

sweden_horror_model <- lm(rating ~ Sweden*Topic_6, data = dat_kaggle)
summary(sweden_horror_model)

<<<<<<< Updated upstream
=======
japan_horror_model <- lm(rating ~ Japan*Topic_6, data = dat_kaggle)
summary(japan_horror_model)

<<<<<<< HEAD
stargazer(sk_horror_model,sweden_horror_model,japan_horror_model,
          type = "text", out = "Table 4", 
          title = "Who Makes Better Horror Movies? South Korea vs.Sweden", 
          omit.stat=c("LL","ser","f","adj.rsq"),
          dep.var.labels.include = FALSE,
          column.labels = c("Rating in SK", "Rating in Sweden",
                            "Rating in Japan"))
# Japanese movies have better rating than SK and Sweden. But for horror movies the effect even decreases. also they don´t effect is high but not significant
=======
>>>>>>> Stashed changes
# romance duration model
long_romance_model <- lm(rating ~ duration*Topic_7, data = dat_kaggle)
summary(long_romance_model)
stargazer(long_romance_model, type="text")
# I think delete this one - not as interesting
<<<<<<< Updated upstream

# romance country
=======
>>>>>>> bc604a3f850c308de8960d080a6e6b347c77a714

# Romance Movies
>>>>>>> Stashed changes
france_romance_model <- lm(rating ~ France*Topic_7, data = dat_kaggle)
summary(france_romance_model)
uk_romance_model <- lm(rating ~ UK*Topic_7, data = dat_kaggle)
summary(uk_romance_model)

stargazer(france_romance_model,uk_romance_model,
          type = "text", out = "Table 5", 
          title = "Who Makes Better Romance Movies? France vs.UK", 
          omit.stat=c("LL","ser","f","adj.rsq"), #omit character vector
          dep.var.labels.include = FALSE,
          column.labels = c("Rating in France", "Rating in UK"))
# a film from france will have a lower rating if it is a romance, 
# but a film from the UK will have a better rating if it is a romance

#Police Model
denmark_crime_model <- lm(rating ~ Denmark*Topic_9, data = dat_kaggle)
sweden_crime_model <- lm(rating ~ Sweden*Topic_9, data = dat_kaggle)
stargazer(denmark_crime_model ,sweden_crime_model,
          type = "text", out = "Table 6", 
          title = "Who Makes Better Police Movies? Denmark vs.Sweden", 
          omit.stat=c("LL","ser","f","adj.rsq"), #omit character vector
          dep.var.labels.include = FALSE,
          column.labels = c("Rating in Denmark", "Rating in Sweden"))
#Denmark police movies have better movies than Sweden

# USA model
usa_crime_model <- lm(rating ~ USA*Topic_9, data = dat_kaggle)
usa_fiction_model<- lm(rating ~ USA*Topic_1, data = dat_kaggle)
summary(usa_crime_model)
summary(usa_fiction_model)
stargazer(usa_crime_model,usa_fiction_model,
          type = "text", out = "Table 7", 
          title = "USA: Crime & Fiction Movies", 
          omit.stat=c("LL","ser","f","adj.rsq"), #omit character vector
          dep.var.labels.include = FALSE,
          column.labels = c("Rating of Crime Movies", "Rating of Finction Movies"))
# USA-made killer-cop-gang-serial films seem to be better than
# the average USA-made film

# India duration interaction effect model
india_len_model <- lm(rating ~ India*duration, data = dat_kaggle)
summary(india_len_model)
stargazer(india_len_model,
          type = "text", out = "Table 8", 
          title = "India: Are Longer Movies better than other Movies?", 
          omit.stat=c("LL","ser","f","adj.rsq"), #omit character vector
          dep.var.labels.include = FALSE,
          column.labels = c("Rating"))
# we know from above that indian films tend to have higher ratings
# longer films have higher ratings
# but when films are from india, a longer film has a lower rating


#PLM 
unit_fe_kaggle <- plm(rating ~ duration + Topic_1 + Topic_2 + Topic_3+ Topic_4+ Topic_5+ Topic_6 + Topic_7 + Topic_8 + Topic_9 + Topic_10, data = dat_kaggle , index = c("country"), model = "within")
stargazer(unit_fe_kaggle,
          type = "text", out = "Table 9", 
          title = "Overall Effect of Rating with each Topic accouting for country", 
          omit.stat=c("LL","ser","f","adj.rsq"), #omit character vector
          dep.var.labels.include = FALSE,
          column.labels = c("Rating"))

###### 2020 DATA ############
dat_2020 <- readRDS("data/dat_2020.rds")

#Change column names
names(dat_2020)[9] <- "Topic_1"
names(dat_2020)[10] <-"Topic_2"
names(dat_2020)[11] <-"Topic_3"
names(dat_2020)[12] <-"Topic_4"
names(dat_2020)[13] <-"Topic_5"
names(dat_2020)[14] <-"Topic_6"
names(dat_2020)[15] <-"Topic_7"
names(dat_2020)[16] <-"Topic_8"
names(dat_2020)[17] <-"Topic_9"
names(dat_2020)[18] <-"Topic_10"

str(dat_2020)
#trasnforming country to categorical variable
dat_2020$country=as.factor(dat_2020$country)

unit_fe_2020<- plm(Rating ~ Duration + Topic_1 + Topic_2 + Topic_3+ Topic_4+ Topic_5+ Topic_6 + Topic_7 + Topic_8 + Topic_9 + Topic_10, data = dat_2020 , index = c("Country"), model = "within")
stargazer(unit_fe_2020, type = "text")

```
