---
title: "R Notebook"
output: html_notebook
---

```{r message = FALSE}
library(rvest)
```

```{r scrape 100 most populat films based on rating}
# Source: IMDb Charts: Most Popular Movies
# Determined by IMDb Users and sorted by Ranking

# Scrape HTML content from a given URL
parsed_url <- read_html("https://www.imdb.com/chart/moviemeter/?ref_=nv_mv_mpm")

# Call node based on xpath
title_nodes <- html_nodes(parsed_url, "a+ .secondaryInfo , #main a")

# Strip the HTML tags and extract title and year 
titles <- html_text(title_nodes)

# Create imdb links to scrape through  
nodes <- html_nodes(parsed_url, "#main a")
sub_urls <- html_attr(nodes, 'href') # extract parts of the link 
sub <- sub_urls[!is.na(sub_urls)]
m_urls <- paste0('http://www.imdb.com', sub) # Concatenate with part that is missing from link

# Function to scrape description 
getdescription <- function(url){
  page <- read_html(url)
  nodes <- html_nodes(page, 'p span')
  cast <- html_text(nodes)
  return(cast)
}

closeAllConnections()

# Use lapply() to apply the getdescription() function to each URL 
description <- lapply(m_urls, getdescription)
# Get rid of duplicates
desc <- unique(description)

closeAllConnections()
```

```{r build dataframe}
# Remove blanks 
col <- titles[!titles %in% c("", " ")]

# Create dataframe 
col1 <- as.data.frame(matrix(col, ncol = 2, byrow = TRUE), 
                      stringsAsFactors = FALSE)

# Remove brackets 
col2[] <- lapply(col1, function(x) gsub("[][(),]", "", x))

# Define column names
colnames(col2) <- c("Title", "Year")

# Add description column
col3 <- transform(col2, Description =sapply(desc, paste0, collapse=','))


```
